version: "3"
services:
       microserviceweb:
           container_name: microserviceweb
           image: microserviceweb
           restart: always
           build: .
           ports:
             - "3000:3000"
           links:
             - mongodb
       mongodb:
             container_name: mongodb
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'