version: "3.4"

services:
  nodejs_mongo_docker:
    image: nodejs_mongo_docker
    build: .
    enviroment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: