version: "3"
services:
  microserviceweb:
    container_name: microserviceweb
    image: microserviceweb
    restart: always
    build: .
    ports:
      - "7500:7500"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'